Repository GNOME-Nepal/website, pull requests merged in 2024-10, with the labels that each got.

#33 Maintained Dark Mode Compatibility enhancing ui
  README.md
  src/App.jsx
  src/components/Accordian.jsx
  src/components/Links.jsx
  src/components/Navbar.jsx
  src/components/mode-toggle.jsx
  src/components/theme-provider.jsx
  src/components/ui/button.jsx
  src/components/ui/card.jsx
  src/components/ui/input.jsx
  src/data/data.js
  src/index.css
  src/sections/Aboutus.jsx
  src/sections/Events.jsx
  src/sections/FAQ.jsx
  src/sections/Newsletter.jsx
  yarn.lock
Labels: hacktoberfest-accepted

#42 ISSUE#39: Text overflow in contributions card
  src/components/ContributorsDetails.jsx
  src/components/ui/carousel.jsx
Labels: bug, hacktoberfest

#48 feat: setup dynamic contributors list #47
  package.json
  src/components/ContributorsDetails.jsx
  src/sections/Contributors.jsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
